
spring:
  datasource:
    url: jdbc:sqlserver://210.103.143.194:19;database=DEV_APP
    username: sa
    password: 119aselcni!.@1
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

server:
  port: 80
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace